In [1]:
import torch
import numpy as np


In [2]:
zero = torch.zeros(2,3)
print(zero)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
one = torch.ones(3,3,3)
print(one)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [5]:
a=torch.tensor([1.,3.,5.])

In [6]:
print(a)

tensor([1., 3., 5.])
