In [1]:
import torch
import numpy as np


In [2]:
zero = torch.zeros(2,3)
print(zero)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
one = torch.ones(3,3,3)
print(one) 

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [ ]:
a= torch.tensor([1.,3.,5.]) 

In [6]:
print(a)

tensor([1., 3., 5.])


In [7]:
arr = np.array([12,3,4,5,2,56])
print(arr)

[12  3  4  5  2 56]


In [8]:
print(type(arr))
print(type(a))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
